name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          check-latest: true

      - name: Install deps
        run: npm ci
        env:
          EXPO_NO_TELEMETRY: 1

      - name: Build web export
        run: npm run build
        env:
          EXPO_NO_TELEMETRY: 1

      - name: Upload artifact (dist)
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: "dist"
